### ISSUE TITLE
Question: Quickstart

### ISSUE THREAD

**Issue by JavierMares** [korniichuk/rk#1]
Hi,

I followed the instructions, using iPython 3.1.0. When creating the new "Template" notebook, it will connect for a few seconds, and then begin a loop between "Dead kernel" and "Connected" notifications. 

Thank you in advance.

**Comment by korniichuk** [comment]
Quickstart here: https://github.com/korniichuk/rk#quickstart
Next time, please, just copy here info about errors from your terminal.
**I have not enough information, maybe you just forget change `kernel.json` file?**
1. Setup SSH for auto login without a password:
https://github.com/korniichuk/rk#setup-ssh-for-auto-login-without-a-password
`$ rk ssh`
2.  Install a template of a remote jupyter kernel:
https://github.com/korniichuk/rk#install-a-template-of-a-remote-jupyter-kernel
`$ rk install-template`
3.  Change the `kernel.json` file:
 `$ sudo gedit /usr/local/share/jupyter/kernels/template/kernel.json`
From:

```
{
 "argv": [
  "rkscript",
  "python",
  "{connection_file}",
  "remote_username@remote_host"
 ],
 "display_name": "Template",
 "language": "python"
}
```

To:

```
{
 "argv": [
  "rkscript",
  "python",
  "{connection_file}",
  "albert@192.168.0.1"
 ],
 "display_name": "Template",
 "language": "python"
}
```

Note:
For a python2 remote jupyter kernel just change value `remote_username@remote_host`.

**Comment by korniichuk** [comment]
YouTube video in Quickstart:
https://github.com/korniichuk/rk#quickstart
