### ISSUE TITLE
Portability: Windows

### ISSUE THREAD

**Issue by dennissergeev** [korniichuk/rk#5]
Hi,

I tried to run `rk install-template` on Windows 7 and it failed with the following error:

```
C:\Anaconda>rk install-template
Traceback (most recent call last):
  File "c:\anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda\Scripts\rk.exe\__main__.py", line 5, in <module>
  File "c:\anaconda\lib\site-packages\rk\rk.py", line 7, in <module>
    from os import link, listdir, makedirs, remove, strerror
ImportError: cannot import name link
```

(As you can see, I'm using Anaconda distribution)

Is the utility is compatible with Windows? What would you recommend?

Cheers,
Denis

**Comment by korniichuk** [comment]
Hi Denis,

**Error:**
`os.link(source, link_name)` -- create a hard link pointing to source named link_name.
Availability: Unix.
https://docs.python.org/2/library/os.html#os.link

**Portability:**
Operating System :: POSIX :: Linux
https://pypi.python.org/pypi/rk

**Recommendation:**
Alternative remote jupyter kernel/kernels administration utility: https://bitbucket.org/tdaff/remote_ikernel
VM: https://www.virtualbox.org/wiki/Downloads
Docker: https://docs.docker.com/engine/installation/windows/
Docker images: https://hub.docker.com/u/jupyter/ and/or https://hub.docker.com/u/korniichuk/
